akvo/akvo-flow-services

config/server/etc/init/flow-services.conf
* -Dfile.encoding=UTF-8 to ensure UTF-8 encoding
* Increase maximum heap size from 1g to 7g (-Xmx7g)
=> [#82] Update flow-services command line args

project.clj
Try to solve the issue by upgrading the GAE SDK
=> [#87] Update GAE SDK

src/akvo/flow_services/uploader.clj
* Remove notifications concurrency
* Wait 1 sec between notifications
=> [#98] Throttle gae notifications

src/akvo/flow_services/uploader.clj
This reverts commit 6bb8f7acb4f3458cced4dd36fe056daa8559dfda.
=> Revert "[#98] Throttle gae notifications"

src/akvo/flow_services/cascade.clj
* Update schema
* Insert new values
=> [#104] Add casacade code to SQLite database

src/akvo/flow_services/uploader.clj
* Additionally address the limitation of GAE `String` types
=> [#108] Fix error message concatenation

src/akvo/flow_services/uploader.clj
* This enables retrieveing results containing over 300 entities from GAE
=> [#129] Use akvo commons  query library to retrieve question ids list

backend/src/akvo/flow_services/cascade.clj, backend/src/akvo/flow_services/email.clj, backend/src/akvo/flow_services/exporter.clj, backend/src/akvo/flow_services/geoshape_export.clj, backend/test/akvo/flow_services/email_test.clj, docker-compose.yml, gae-dev-server/Dockerfile, gae-dev-server/settings.xml
Removing all urls, emails and secrets. 
Moving all urls and emails to debug level.
=> Issues 176/logging sensitive data

ci/test/deploy.sh
Increasing mem to 6gb in prod and 2gb in test
Fixes #187
=> [#187] Increasing the mem and cpu limits

backend/src/akvo/flow_services/uploader.clj
=> [#195] Fix Zip Slip vulnerability

backend/src/akvo/flow_services/uploader.clj
Fixes #203
Changing log level to info. User already notified via UI
=> Do not report sentry errors on "Errors in raw data upload"

backend/src/akvo/flow_services/core.clj
Fixes #205
Returning 400 instead
=> NPE if baseUrl is null

backend/src/akvo/flow_services/core.clj
org.waterforpeople and com.gallatinsystems were missing as Akvo's packages
Fixes: #210
=> Configure all of Akvo's packages in logging

backend/resources/en.properties, backend/resources/es.properties, backend/resources/ui-strings.properties
Email template updated to match "Simple" option in issue.
=> [#1334]Update email template. (Connect #1334)

doc/RunningLocally.md
=> Document dev workflow when working on Flow Java classes

backend/src/akvo/flow_services/stats.clj, backend/test/akvo/flow_services/end_to_end_stats_test.clj, backend/test/akvo/flow_services/stats_test.clj, backend/test/akvo/flow_services/test_util.clj, ci/test/build.sh, ci/test/deploy.sh
=> Adding test to stats functionaliity

backend/project.clj
Bumping the classes to deploy changes in https://github.com/akvo/akvo-flow/issues/2777
=> [#171] Bump classes version

backend/src/akvo/flow_services/scheduler.clj, backend/test/akvo/flow_services/end_to_end_geoshape_test.clj, backend/test/akvo/flow_services/end_to_end_test.clj, backend/test/akvo/flow_services/export_job_test.clj, backend/test/akvo/flow_services/test_util.clj
Removing old logic and update the tests to always expect the flow report
API to be called
Fixes [#230]
=> Remove non-GDPR path

backend/project.clj
This contains the full form export feature.
=> [#171]Bump version for Key Kalmia release

backend/src/akvo/flow_services/cascade.clj, backend/test/akvo/flow_services/cascade_test.clj
Using a vector of values instead of str concatenation
Fixes #235
=> String concatenation is not safe.

backend/src/akvo/flow_services/geoshape_export.clj, backend/test/akvo/flow_services/geoshape_export_test.clj
No validation of coordinates in either case
Fixed #239
=> Adding LineString and MultiPoint support

backend/src/akvo/flow_services/core.clj, backend/test/akvo/flow_services/end_to_end_geoshape_test.clj, backend/test/akvo/flow_services/end_to_end_test.clj, backend/test/akvo/flow_services/test_util.clj
Also, being more specific about the content-type of the xlsx files
Fixes #246
=> Adding Content-Disposition header

.travis.yml, backend/src/akvo/flow_services/uploader.clj, backend/test/akvo/flow_services/uploader_test.clj
Fixes #251
If no zip files found in the unzipped directory, use the original zip file
=> Be more lenient with the format of the bulk upload

backend/src/akvo/flow_services/geoshape_export.clj, backend/test/akvo/flow_services/geoshape_export_test.clj
Partial fix for #245. See issue for more details.
Do not keep just the iteration 0 responses.
Added "Repeat No" starting from 1 for each feature.
=> Repeated groups in geoshapes

backend/src/akvo/flow_services/uploader.clj, backend/test/akvo/flow_services/uploader_test.clj
Special case for 0 data files, hinting the user that the uploaded file is probably incorrect
Fixes #253
=> Bulk upload user message contains the number of uploaded files

backend/project.clj
Fixes form import verification bug
=> [#171]Bump jar version for flow issue #2995 verification fix..
